"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var analytics_controller_1 = require("../controllers/analytics.controller");
var auth_middleware_1 = require("../middleware/auth.middleware");
var router = (0, express_1.Router)();
var controller = new analytics_controller_1.AnalyticsController();
router.use(auth_middleware_1.authenticate);
router.get('/dashboard', controller.getDashboardStats);
router.get('/top-posts', controller.getTopPosts);
router.get('/post/:postId', controller.getPostAnalytics);
exports.default = router;
