"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_controller_1 = require("../controllers/auth.controller");
var auth_middleware_1 = require("../middleware/auth.middleware");
var social_controller_1 = require("../controllers/social.controller");
var rate_limit_1 = require("../middleware/rate-limit");
var router = (0, express_1.Router)();
var authController = new auth_controller_1.AuthController();
var socialController = new social_controller_1.SocialController();
router.post('/register', rate_limit_1.authLimiter, authController.register);
router.post('/login', rate_limit_1.authLimiter, authController.login);
router.get('/me', auth_middleware_1.authenticate, authController.me);
router.post('/logout', auth_middleware_1.authenticate, authController.logout);
exports.default = router;
router.get('/:platform/callback', socialController.callback);
