"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var billing_controller_1 = require("../controllers/billing.controller");
var auth_middleware_1 = require("../middleware/auth.middleware");
var router = (0, express_1.Router)();
var controller = new billing_controller_1.BillingController();
router.post('/webhook', controller.handleWebhook);
router.use(auth_middleware_1.authenticate);
router.get('/status', controller.getStatus);
router.post('/checkout', controller.createCheckout);
exports.default = router;
