"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contentRouter = void 0;
var express_1 = require("express");
var auth_middleware_1 = require("../middleware/auth.middleware");
var content_controller_1 = require("../controllers/content.controller");
exports.contentRouter = (0, express_1.Router)();
var contentController = new content_controller_1.ContentController();
exports.contentRouter.use(auth_middleware_1.authenticate);
exports.contentRouter.post('/', contentController.createPost);
exports.contentRouter.get('/', contentController.getPosts);
exports.contentRouter.put('/:id', contentController.updatePost);
exports.contentRouter.delete('/:id', contentController.deletePost);
exports.contentRouter.post('/:id/cancel', contentController.cancelPost);
