"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var crm_controller_1 = require("../controllers/crm.controller");
var auth_middleware_1 = require("../middleware/auth.middleware");
var router = (0, express_1.Router)();
var controller = new crm_controller_1.CrmController();
router.use(auth_middleware_1.authenticate);
router.get('/deals', controller.getDeals);
router.post('/deals', controller.createDeal);
router.get('/deals/:id', controller.getDealById);
router.put('/deals/:id', controller.updateDeal);
router.delete('/deals/:id', controller.deleteDeal);
exports.default = router;
