"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_middleware_1 = require("../middleware/auth.middleware");
var growth_controller_1 = require("../controllers/growth.controller");
var router = (0, express_1.Router)();
var controller = new growth_controller_1.GrowthController();
router.use(auth_middleware_1.authenticate);
router.get('/score', controller.getGrowthScore);
router.get('/best-times', controller.getBestTimes);
router.get('/content-analysis', controller.getContentAnalysis);
router.get('/recommendations', controller.getRecommendations);
exports.default = router;
