"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var inbox_controller_1 = require("../controllers/inbox.controller");
var auth_middleware_1 = require("../middleware/auth.middleware");
var router = (0, express_1.Router)();
var controller = new inbox_controller_1.InboxController();
router.use(auth_middleware_1.authenticate);
router.get('/', controller.getItems);
router.post('/:id/reply', controller.reply);
router.post('/:id/read', controller.markRead);
router.post('/:id/like', controller.toggleLike);
router.post('/:id/hide', controller.toggleHide);
router.delete('/:id', controller.deleteItem);
exports.default = router;
